/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Escrow: () => import('#controllers/escrow_controller'),
  Fleets: () => import('#controllers/fleets_controller'),
  LoadDocuments: () => import('#controllers/load_documents_controller'),
  Loads: () => import('#controllers/loads_controller'),
  Me: () => import('#controllers/me_controller'),
}
