/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type DriverProfileTransformer from '#transformers/driver_profile_transformer'
import type FleetDriverTransformer from '#transformers/fleet_driver_transformer'
import type FleetTransformer from '#transformers/fleet_transformer'
import type LoadDocumentTransformer from '#transformers/load_document_transformer'
import type LoadEventTransformer from '#transformers/load_event_transformer'
import type LoadTransformer from '#transformers/load_transformer'
import type ShipperProfileTransformer from '#transformers/shipper_profile_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type VehicleTransformer from '#transformers/vehicle_transformer'

export namespace Data {
  export type DriverProfile = InferData<DriverProfileTransformer>
  export namespace DriverProfile {
    export type Variants = InferVariants<DriverProfileTransformer>
  }
  export type FleetDriver = InferData<FleetDriverTransformer>
  export namespace FleetDriver {
    export type Variants = InferVariants<FleetDriverTransformer>
  }
  export type Fleet = InferData<FleetTransformer>
  export namespace Fleet {
    export type Variants = InferVariants<FleetTransformer>
  }
  export type LoadDocument = InferData<LoadDocumentTransformer>
  export namespace LoadDocument {
    export type Variants = InferVariants<LoadDocumentTransformer>
  }
  export type LoadEvent = InferData<LoadEventTransformer>
  export namespace LoadEvent {
    export type Variants = InferVariants<LoadEventTransformer>
  }
  export type Load = InferData<LoadTransformer>
  export namespace Load {
    export type Variants = InferVariants<LoadTransformer>
  }
  export type ShipperProfile = InferData<ShipperProfileTransformer>
  export namespace ShipperProfile {
    export type Variants = InferVariants<ShipperProfileTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Vehicle = InferData<VehicleTransformer>
  export namespace Vehicle {
    export type Variants = InferVariants<VehicleTransformer>
  }
}
