/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { MarketCode, Fleet, StatusActor, LoadStatus, CargoDetails, CargoType, UserRole, BodyType, Vehicle, VehicleClass } from '@a2b/core'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverProfileSchema extends BaseModel {
  static $columns = ['completedTrips', 'createdAt', 'dutyStatus', 'fleetId', 'id', 'licenseClass', 'licenseNumber', 'ratingAvg', 'updatedAt', 'userId', 'verificationStatus'] as const
  $columns = DriverProfileSchema.$columns
  @column()
  declare completedTrips: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dutyStatus: 'AVAILABLE' | 'OFF_DUTY'
  @column()
  declare fleetId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licenseClass: string | null
  @column()
  declare licenseNumber: string | null
  @column()
  declare ratingAvg: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare verificationStatus: 'PENDING' | 'VERIFIED' | 'REJECTED'
}

export class EscrowSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'depositMethod', 'heldAt', 'id', 'loadId', 'refundedAt', 'releaseAttempts', 'releaseCodeExpiresAt', 'releaseCodeHash', 'releasedAt', 'status', 'updatedAt'] as const
  $columns = EscrowSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare depositMethod: string | null
  @column.dateTime()
  declare heldAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loadId: number
  @column.dateTime()
  declare refundedAt: DateTime | null
  @column()
  declare releaseAttempts: number
  @column.dateTime()
  declare releaseCodeExpiresAt: DateTime | null
  @column()
  declare releaseCodeHash: string | null
  @column.dateTime()
  declare releasedAt: DateTime | null
  @column()
  declare status: 'AWAITING_DEPOSIT' | 'HELD' | 'RELEASED' | 'REFUNDED'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FleetSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'id', 'market', 'name', 'ownerId', 'primaryCorridor', 'sizeTier', 'taxId', 'updatedAt'] as const
  $columns = FleetSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare market: MarketCode
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column()
  declare primaryCorridor: string | null
  @column()
  declare sizeTier: Fleet['sizeTier']
  @column()
  declare taxId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LoadDocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'fileKey', 'id', 'loadId', 'mimeType', 'originalName', 'requirementId', 'sizeBytes', 'updatedAt', 'uploadedBy'] as const
  $columns = LoadDocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileKey: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loadId: number
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare requirementId: string
  @column()
  declare sizeBytes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadedBy: number
}

export class LoadEventSchema extends BaseModel {
  static $columns = ['actorId', 'actorRole', 'createdAt', 'fromStatus', 'id', 'loadId', 'note', 'toStatus'] as const
  $columns = LoadEventSchema.$columns
  @column()
  declare actorId: number | null
  @column()
  declare actorRole: StatusActor
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatus: LoadStatus | null | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loadId: number
  @column()
  declare note: string | null
  @column()
  declare toStatus: LoadStatus
}

export class LoadLocationSchema extends BaseModel {
  static $columns = ['createdAt', 'dropoffAddress', 'dropoffLat', 'dropoffLng', 'id', 'loadId', 'pickupAddress', 'pickupContactName', 'pickupContactPhone', 'pickupLat', 'pickupLng', 'receiverName', 'receiverPhone', 'updatedAt'] as const
  $columns = LoadLocationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dropoffAddress: string
  @column()
  declare dropoffLat: number | null
  @column()
  declare dropoffLng: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loadId: number
  @column()
  declare pickupAddress: string
  @column()
  declare pickupContactName: string | null
  @column()
  declare pickupContactPhone: string | null
  @column()
  declare pickupLat: number | null
  @column()
  declare pickupLng: number | null
  @column()
  declare receiverName: string | null
  @column()
  declare receiverPhone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LoadSchema extends BaseModel {
  static $columns = ['cancelledAt', 'cargo', 'cargoType', 'completedAt', 'containerId', 'createdAt', 'deadlineAt', 'deliveredAt', 'driverId', 'dropoffSummary', 'fleetId', 'id', 'inTransitAt', 'isImport', 'market', 'matchedAt', 'offerPrice', 'pickupSummary', 'postedAt', 'readyAt', 'reference', 'securedAt', 'shipperId', 'status', 'updatedAt', 'vehicleId', 'weightKg'] as const
  $columns = LoadSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cargo: CargoDetails
  @column()
  declare cargoType: CargoType
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare containerId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deadlineAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare driverId: number | null
  @column()
  declare dropoffSummary: string
  @column()
  declare fleetId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare inTransitAt: DateTime | null
  @column()
  declare isImport: boolean
  @column()
  declare market: MarketCode
  @column.dateTime()
  declare matchedAt: DateTime | null
  @column()
  declare offerPrice: number
  @column()
  declare pickupSummary: string
  @column.dateTime()
  declare postedAt: DateTime | null
  @column.dateTime()
  declare readyAt: DateTime | null
  @column()
  declare reference: string
  @column.dateTime()
  declare securedAt: DateTime | null
  @column()
  declare shipperId: number
  @column()
  declare status: LoadStatus
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number | null
  @column()
  declare weightKg: number | null
}

export class PaymentTransactionSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'escrowId', 'id', 'kind', 'method', 'provider', 'providerRef', 'raw', 'status', 'updatedAt'] as const
  $columns = PaymentTransactionSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare escrowId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: 'DEPOSIT' | 'PAYOUT' | 'REFUND'
  @column()
  declare method: string
  @column()
  declare provider: string
  @column()
  declare providerRef: string | null
  @column()
  declare raw: Record<string, unknown> | null | null
  @column()
  declare status: 'PENDING' | 'SUCCEEDED' | 'FAILED'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PhoneOtpSchema extends BaseModel {
  static $columns = ['attempts', 'codeHash', 'consumedAt', 'createdAt', 'expiresAt', 'id', 'phone'] as const
  $columns = PhoneOtpSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare codeHash: string
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string
}

export class ShipperProfileSchema extends BaseModel {
  static $columns = ['companyName', 'createdAt', 'id', 'isImporter', 'region', 'taxId', 'updatedAt', 'userId'] as const
  $columns = ShipperProfileSchema.$columns
  @column()
  declare companyName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isImporter: boolean
  @column()
  declare region: string | null
  @column()
  declare taxId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'fullName', 'id', 'market', 'phone', 'phoneVerifiedAt', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare market: MarketCode
  @column()
  declare phone: string
  @column.dateTime()
  declare phoneVerifiedAt: DateTime | null
  @column()
  declare role: UserRole
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleSchema extends BaseModel {
  static $columns = ['assignedDriverId', 'bodyType', 'capacityTons', 'createdAt', 'fleetId', 'id', 'make', 'market', 'model', 'ownerUserId', 'plate', 'status', 'updatedAt', 'vehicleClass'] as const
  $columns = VehicleSchema.$columns
  @column()
  declare assignedDriverId: number | null
  @column()
  declare bodyType: BodyType
  @column()
  declare capacityTons: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fleetId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare make: string
  @column()
  declare market: MarketCode
  @column()
  declare model: string
  @column()
  declare ownerUserId: number | null
  @column()
  declare plate: string
  @column()
  declare status: Vehicle['status']
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleClass: VehicleClass
}
