import { configApp } from '@adonisjs/eslint-config'

export default configApp(
  {
    // Regenerated by Lucid after every migration
    ignores: ['database/schema.ts'],
  },
  {
    // Tests read clearer as `(await client.post(...)).assertStatus(...)`
    files: ['tests/**/*.ts'],
    rules: { '@unicorn/no-await-expression-member': 'off' },
  }
)
